### PR TITLE
Enforce unique bus numbers

### LINKED ISSUE #364: bus numbers aren't required to be unique
```julia
julia> s = System(nothing)
┌ Error: Model doesn't contain a slack bus
└ @ PowerSystems ~/Documents/repos/PowerSystems.jl/src/utils/IO/system_checks.jl:25
┌ Warning: Bus/Nodes data does not contain information to build an a network
└ @ PowerSystems ~/Documents/repos/PowerSystems.jl/src/utils/IO/system_checks.jl:9
System
======
Base Power: 100.0

Components
==========
Num components: 4

4×3 DataFrames.DataFrame
│ Row │ ConcreteType    │ SuperTypes                                                                                                            │ Count │
│     │ String          │ String                                                                                                                │ Int64 │
├─────┼─────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────┤
│ 1   │ Bus             │ Topology <: Component <: PowerSystemType <: InfrastructureSystemsType <: Any                                          │ 1     │
│ 2   │ PowerLoad       │ StaticLoad <: ElectricLoad <: Injection <: Device <: Component <: PowerSystemType <: InfrastructureSystemsType <: Any │ 1     │
│ 3   │ RenewableFix    │ RenewableGen <: Generator <: Injection <: Device <: Component <: PowerSystemType <: InfrastructureSystemsType <: Any  │ 1     │
│ 4   │ ThermalStandard │ ThermalGen <: Generator <: Injection <: Device <: Component <: PowerSystemType <: InfrastructureSystemsType <: Any    │ 1     │

Forecasts
=========
Resolution: 0 minutes
Horizon: 0
Interval: 0 minutes
Num initial times: 0
Num forecasts: 0

---------------------------------


julia> b1 = Bus(1, "one", "PV", 0.0, 1.0, (min=0.95, max=1.05), 100.0)
one (Bus):
   number: 1
   name: one
   bustype: PV
   angle: 0.0
   voltage: 1.0
   voltagelimits: (min = 0.95, max = 1.05)
   basevoltage: 100.0

julia> add_component!(s, b1)

julia> b2 = Bus(1, "two", "PV", 0.0, 1.0, (min=0.95, max=1.05), 100.0)
two (Bus):
   number: 1
   name: two
   bustype: PV
   angle: 0.0
   voltage: 1.0
   voltagelimits: (min = 0.95, max = 1.05)
   basevoltage: 100.0

julia> add_component!(s, b2)

julia> get_bus(s,1)
two (Bus):
   number: 1
   name: two
   bustype: PV
   angle: 0.0
   voltage: 1.0
   voltagelimits: (min = 0.95, max = 1.05)
   basevoltage: 100.0
```

### PR DESCRIPTION
**Pull request by daniel-thom**
This will fix issue and close #364

### CODE REVIEW

File: test/test_system.jl [hunk 1]
```diff
@@ -51,15 +51,53 @@
                             "rating")
     @test forecast isa Deterministic
 
-    @test get_forecasts_horizon(sys) == 24
+    horizon = get_forecasts_horizon(sys)
+    @test horizon == 24
     @test get_forecasts_initial_time(sys) == Dates.DateTime("2020-01-01T00:00:00")
     @test get_forecasts_interval(sys) == Dates.Hour(0)
```
Comment (jd-lara) [inline test/test_system.jl]: Seems that get_forecast_interval will only make sense now if we have more than one forecast or the forecasts are in chunks.
