### PR TITLE
Fix per unit

### LINKED ISSUE #98: parsing MATPOWER file scales generator MW values by 1/100
```julia
# from matpower file
sys_UC.generators.thermal[1].tech
TechThermal(3.24498, (min = 2.6, max = 5.2), 3.9, (min = -3.9, max = 3.9), (up = 0.0, down = 0.0), nothing)
```

```julia
# from .jl file
sys_UC_psst.generators.thermal[3].tech
TechThermal(520.0, (min = 260.0, max = 520.0), 100.0, (min = -390.0, max = 390.0), nothing, nothing)
```

### PR DESCRIPTION
**Pull request by claytonpbarrows**
this PR resolves #98

### CODE REVIEW

**Comment by kdheepak** [comment]
Great! Looks good. But you've rebased on top of a separate PR. So we cannot merge both now. I suggest that we review this but not merge it yet. Once the other PR has been merged I can rebase on top of origin/master, remove duplicate commits and then merge this tests pass.

File: src/parsers/standardfiles_parser.jl [hunk 1]
```diff
@@ -2,6 +2,9 @@ function parsestandardfiles(file::String)
 
     data = parse_file(file)
 
+    #make sure that data is mixed units
+    make_mixed_units(data)
```
Comment (kdheepak) [inline src/parsers/standardfiles_parser.jl]: Make this `PM.make_mixed_units` instead of `make_mixed_units`.

File: test/parsestandard.jl [hunk 2]
```diff
@@ -15,6 +15,8 @@ for f in files
         @info "Parsing $f ..."
         pm_dict = PowerSystems.parse_file(abspath(joinpath(dirname(Base.find_package("PowerSystems")), "../data/matpower",f)))
         @info "Successfully parsed $f to PowerModels dict"
+        make_mixed_units(pm_dict)
```
Comment (kdheepak) [inline test/parsestandard.jl]: Make this PM.make_mixed_units instead of make_mixed_units.

File: test/parsestandard.jl [hunk 3]
```diff
@@ -42,6 +44,8 @@ for f in files
         @info "Parsing $f ..."
         pm_dict = PowerSystems.parse_file(abspath(joinpath(dirname(Base.find_package("PowerSystems")), "../data/psse_raw",f)))
         @info "Successfully parsed $f to PowerModels dict"
+        make_mixed_units(pm_dict)
```
Comment (kdheepak) [inline test/parsestandard.jl]: Make this PM.make_mixed_units instead of make_mixed_units.
